FROM php:7.4-apache

MAINTAINER mefizz <mefizz@gmail.com>

ARG USER_ID
ARG GROUP_ID


RUN apt update \
   && apt install -y tzdata \

   libicu-dev \
   git \
   wget \
   curl \
   zlib1g-dev \
   libzip-dev \
   openssh-client \
   libfreetype6-dev \
   libjpeg62-turbo-dev \
   libonig-dev \
   libmcrypt-dev \
   libpng-dev


RUN pecl install xdebug-2.9.6 \

    && docker-php-ext-enable xdebug \
    && a2enmod rewrite \
    && docker-php-ext-install pdo_mysql intl zip \
    && docker-php-ext-configure gd \
    && docker-php-ext-install -j$(nproc) gd


RUN rm -rf /var/log/apache2/*


ADD ./environment/php.ini $PHP_INI_DIR/
ADD ./environment/custom.ini /usr/local/etc/php/conf.d/
COPY ./environment/custom.ini /etc/php/7.4/cli/conf-d/40-custom.ini
COPY ./environment/custom.ini /etc/php/7.4/apache2/conf-d/40-custom.ini


RUN rm -f /etc/apache2/sites-available/000-default.conf
ADD ./environment/000-default.conf /etc/apache2/sites-available/



RUN chown -R www-data:www-data /var/www/html/
RUN chown -R www-data:www-data /var/log/apache2/



ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid


RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
WORKDIR /var/www/html

EXPOSE 80




